### PR TITLE
more emoji mapping

### LINKED ISSUE #10: a few more emoji replacements?
Could we add some more emoji mappings? -- such as:

`:no_entry_sign:` => 🚫
`:bust_in_silhouette:` => 👤
`:star:` => ⭐
`:blue_heart:` => 💙
`:heart:` => ❤️ 
`:mega:` => 📣
`:raising_hand:` => 🙋
`:slightly_smiling_face:` => 🙂
`:thumbsup:` => 👍

----

Possible complications that comes to mind:
* Skin tones on raised hand and thumbs up, depending on the Slack settings of whoever runs the meeting.  Maybe just something to note, and see how things go, not worry about right now.
* Will the no-entry/bust-silhouette mappings mess with the redacting + anonymizing treatment?

### PR DESCRIPTION
**Pull request by alisonjo315**
fixes #10

### CODE REVIEW

**Comment by goba** [comment]
Yeah I think this will mess with the :bust_in_silhouette: and the :no-entry-sign: treatment below, since that is matched after the parsing is done. So those would need to be updated as well.

**Comment by alisonjo315** [comment]
Ahhhhh good point.  Do you think the emoji mapping can go after `parseThread`?

If not, I think I'll just remove those two lines, and not worry about automating these two emoji replacements.  MAYBE I'll create a follow-up "nice to have" issue for automating those two emoji replacements without breaking the redaction treatment.

**Comment by goba** [comment]
I think its better to update the behaviour to match the emoji and test manually that it works. It should #famouslastwords

**Comment by alisonjo315** [comment]
Cool!  Done, I think 🤞

**Comment by goba** [comment]
Ok I manually tested this and it worked great. I did a little thread with myself in slack. Thanks a lot!
Screenshot 2022-10-03 at 20 29 56

**Pull request merged**
